== Overview

=== What is BigTIFF
The TIFF file format uses 32bit offsets and, as such, is limited to 4 GBytes. This has been quite sufficient for many years. Today however, there is a need for a good multi-purpose open image file format that can handle huge images, or very large collections of images, breaking the 4 GBytes boundary.

BigTIFF is backward compatible with parts original TIFF and extends the same idea. This way, existing TIFF libraries can quite easily extend their support for TIFF to also include BigTIFF support. This results in a very short list of requirements. All the much appreciated properties of the TIFF format and have been extended for more than a decade are inherited. All properly known TIFF tags can be reused, all supported bit-depths and datatypes remain valid. The arbitrary number of 'extra channels', the tiling and striping schemes, the multitude of compression schemes, and the private tag scheme, that made TIFF very useful in pre-press as well as for storing scientific data, and many other applications, all remain intact. By changing the offset bit-depth, BigTIFF files are no longer restrained by the 4 GByte limitation from which TIFF suffers. The BigTIFF format is based on the TIFF format and depends on the TIFF specification.

=== Origin and compatibility

This Standard collects an attempt to launch a new variant of TIFF, called BigTIFF, that closely resembles TIFF, but uses 64bit offsets instead. The results of the BigTIFF discussion resulted in an original specification exposed in the Aware Systems website: https://www.awaresystems.be/imaging/tiff/bigtiff.html. Aware Systems is managed by Joris Van Damme. This Standard starts with Joris Van Damme initial work and translates it into an OGC standard. Another source of information on the BigTIFF format is the BigTIFF design page at the LibTiff site http://bigtiff.org/.

There are at least two independent implementations of the original BigTIFF specification. (AWare Systems AsTiff, and LibTiff since version 4.0). This OGC Standard does not contradicts the original BigTIFF specification so the implementations of BigTIFF are immediatelly compatible with this Standard.

=== Changes to the original version

In the elaboration of this Standard a new naming for the data types have been adopted.

[#classic-tiff-file-header,reftext='{table-caption} {counter:table-num}']
.Changes in data types.
[width = "100%",options="header"]
|===
| Original | Adopted | Description
| Word | uint16 | unsigned short integer (2 bytes)
| Unsigned long | uint32 | unsigned long integer (4 bytes)
| Signed 8Byte  | int64 | signed long long integer (8 bytes)
| Unsigned 8Byte	| uint64 | unsigned long long integer (8 bytes)
|===
