[big]*i.     Abstract*

This document is OGC Standard that describes an extended internal structure for a image file that requires more than 4GBytes. The general structure is similar to the TIFF specification version 6 but it replaces two essential data structures called Image File Header and Image File Directory for new ones that support the necessary longer integer numbers that acts as internal offsets of the file. It also adds 3 new data types for very long integers. It is expected that other OGC standards, such as GeoTIFF, can support BigTIFF in the near future.

[big]*ii.    Keywords*

The following are keywords to be used by search engines and document catalogues.

ogcdoc, OGC document, TIFF, image format

[big]*iii.   Preface*

When the TIFF format was defined back in 1986 the storage capacity of the computers made difficult to image that a single file could ever be bigger than 4GBytes long. But today capacities makes it possible and if the file can be random accessed in small pieces, could be even useful to have a big remote sensing product in a single file.

The basic BigTIFF design was first proposed in 2004 and refined in (https://www.asmail.be/msg0055453930.html)[this discussion] on the (https://www.awaresystems.be/)[Aware Systems] mailing list.  Contributors to the design discussion included Joris Van Damme, Lynn Quam, Frank Warmerdam, Chris Cox, Rob Tillaart, Dan Smith, Bob Freisenhahn, Andrey Kiselev, Phillip Crews, and Gerben Vos.
The BigTIFF format was proposed in https://www.awaresystems.be/imaging/tiff/bigtiff.html maintained by Joris Van Damme and has been stable in recent years.

GeoTIFF 1.1 was brought to the OGC as a community standard but, in the process, was made dependent form the classical TIFF specification. This document brings BigTIFF to the OGC as another community standard. It is expected that Next version of GeoTIFF supports both Classical TIFF and  BigTIFF.

This document is an adaptation of the https://www.awaresystems.be/imaging/tiff/bigtiff.html content to an OGC language to bring it to the OGC standards process as a community standard. It was done with the intention of creating a transcription with no practical modifications, so old BigTIFF implementations would be compatible with this document.

[NOTE]
====
Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.
====

[big]*iv.    Security Considerations*

No security considerations have been made for this Standard.

[big]*v.    Submitting organizations*

The following organizations submitted this Document to the Open Geospatial Consortium (OGC):

* UAB-CREAF

[big]*vi.     Submitters*

All questions regarding this submission should be directed to the editor or the submitters:

|===
|*Name* |*Affiliation*
| Joan Masó | UAB-CREAF
|===
