[obligation=informative]
== Overview

=== What is BigTIFF

The TIFF file format was defined in mid-1980s as an extensible format. At that time 32bit offsets seemed sufficient, giving a limit to a 4 Gibibytes (2^32^) file size. This has been quite sufficient for many years. Today however, there is a need for a good multi-purpose open image file format that can handle huge images, or very large collections of images, that together exceed the 4 Gibibytes (2^32^) boundary.

BigTIFF is very similar to the original TIFF and only changes some internal headers to support 64 bits offsets and data types. The benefits of BigTIFF closely resembling TIFF are huge. For instance, existing TIFF libraries can quite easily extend their support for TIFF to also include this variant. This results in a very short list of requirements. All the much-appreciated properties of the TIFF format that have been around and have been extended for decades are inherited. All properly known tags are being reused, all supported bit depths and datatypes remain valid. The arbitrary number of 'extra channels', the tiling and striping schemes, the multitude of compression schemes, and the private tag scheme, that made TIFF very useful in pre-press as well as for storing scientific data, and many other applications, all remain intact. Yet, by changing the offset bit depth, BigTIFF files are no longer restrained by the 4 Gibibytes (2^32^) limitation from which classic TIFF suffers. 

Since the BigTIFF format is based on the TIFF format, the reader is encouraged to familiarize with the current version of the TIFF specification before reading this.

=== Origin and compatibility

This Standard collects the attempt to launch a new variant of TIFF, called BigTIFF, that closely resembles TIFF, but uses 64bit offsets instead. The results of the BigTIFF discussion resulted in an original specification exposed in the Aware Systems website: https://web.archive.org/web/20240706160214/https://www.awaresystems.be/imaging/tiff/bigtiff.html. Aware Systems was managed by Joris Van Damme but was discontinued after July 6th, 2025 and can only be accessible in backup copies done by the WebAchive iniciative. In order to preserve and consolidate the BigTIFF iniciative, the process of creating this Standard started with Joris Van Damme initial work and was translated it into an OGC standard. Another source of information on the BigTIFF format is the BigTIFF design page at the LibTiff site http://bigtiff.org/.

There are at least two independent implementations of the original BigTIFF specification. (AWare Systems AsTiff, and LibTiff since version 4.0). This OGC Standard does not contradicts the original BigTIFF specification so the implementations of BigTIFF are immediatelly compatible with this Standard.

=== Changes to the original version

In the elaboration of this Standard a new naming for the data types have been adopted for clarity.

[#classic-tiff-file-header,reftext='{table-caption} {counter:table-num}']
.Changes in data types.
[width = "100%",options="header"]
|===
| Original | Adopted | Description
| Word | uint16 | unsigned short integer (2 bytes)
| Unsigned long | uint32 | unsigned long integer (4 bytes)
| Signed 8Byte  | int64 | twos-complement signed long long integer (8 bytes)
| Unsigned 8Byte	| uint64 | unsigned long long integer (8 bytes)
|===

=== Implications for EXIF
EXIF is a metadata standard that uses a TIFF-compatible structure such as _image file header_ and _image file directory_ as a container. It adopts many of the accepted <<AdobeTIFF6>> tags and provides an extra list of EXIF tags and a pointer to a dedicated EXIF sub-IFD.

EXIF extra tags define a photography-focused subset and extends it with standardized metadata fields for digital cameras. It captures information such as exposure, date/time, GPS, and thumbnail-related data. For TIFF files, EXIF information is integrated by adding new TIFF tags. For the JPEG format, EXIF is included in the Application Market Segment (APP1). APP1 is recorded immediately after the SOI marker indicating the beginning of the file.

EXIF specification references Classic TIFF as a data structure and current cameras are not generating images with size bigger that 4Gib. However, nothing prevents a BigTIFF file to use EXIF following the same pattern specified in this Standard (by replacing IFH and IFDs with BIFH and BIFDs respectively). Implementations of EXIF readers should consider the possibility to find BigTIFF structures when reading EXIF, and the need to transform them to Classic TIFF structures when exporting data and metadata to JPEG or other formats.

NOTE: In the future, the structure BigTIFF format could support both IFDs and BIFDs and by saving this EXIF part in the first part of the document this issue could be avoided. However introducing changes in the original BigTIFF specification is out of scope of this Standard.