[[BigTIFFRequirements]]
== BigTIFF requirements
The BigTIFF standard provides a solution for a TIFF file that requires a file size larger than 4 Gibibytes (2^32^). In a BigTIFF file, the largest possible file is 2^64^ bytes in length. In this situation the classic TIFF internal 32 bit offsets are not long enough to point to the a byte beyond the 4 Gibibytes limit.

=== Requirement Class Core

include::../requirements/requirements_class_core.adoc[]

NOTE: This requirement class has _BigTIFF file_ as target of all requirements. Indirectly, the requirements class imposes requirements on a BigTIFF writter (that should deliver a file following these requirements). It also indirectly imposes requirements on how a BigTIFF should operate to understand a BigTIFF file.

include::../recommendations/core/PER_big-offsets.adoc[]

NOTE: Commonly "permissions" are statements that emphasizes the usefulness of some possibilities that may be not obvious, but do not contradict requirements. In this case we are forced to use a permission to overwrite requirements in the original TIFF specification, allowing for 64 bit offsets.

include::../recommendations/core/REC_small-files.adoc[]

NOTE: This is in order to ensure maximum backwards compatibility with old TIFF implementations not supporting BigTIFF.

==== Basic format

include::../requirements/core/big-offsets.adoc[]

NOTE: There is a paradox in the actual 4 Gibibytes limit. In a case that all _Image File Directories_ are at the beginning of the file, a 32 bit offset can be sufficient to point to an array of image strips offsets (Tag code 273) and 32 bit numbers may be sufficient for image strips offsets, but imagining that strips are in other and that the second to last strip is at the offset 4.1 10^9^ and that the last strip is 250 MegaByte long, the total size of the file will cross the 4 GiB boundary. In a case like this, even if BigTIFF it is not technically necessary, a BigTIFF is mandated by this Standard. This provides a clear criteria to discriminate the need for a BigTIFF file that is independent from order and size of the internal parts of the file.

include::../requirements/core/bifh.adoc[]

[#bigtiff-file-header,reftext='{table-caption} {counter:table-num}']
.BigTIFF file header (normative)
[width = "100%",options="header",cols="1h,1,4"]
|===
| Offset {set:cellbgcolor:#EEEEEE} | Datatype | Value
| 0 {set:cellbgcolor:#FFFFFF} | uint16 | Byte order indication (use the values stated in the TIFF version 6 Image File Header Bytes 0-1)
| 2 | uint16 | Version number (always 43)
| 4 | uint16 | Size of offset in bytes. Always 8 in BigTIFF (it could be 16 in a future version for superbig TIFFs)
| 6 | uint16 | Reserved. Populate with 0
| 8 | uint64 | Offset (in bytes) to first BIFD
|===

(The <<annex-classic-tiff-basic-struct-informative>> contains the TIFF version 6 classic structures for comparison purposes).

While the classic TIFF _image file header_ points to the first _Image File Directory_ (IFD), the BigTIFF _big image file header_ points to the first _Big Image File Directory_ (BIFD). In that sense IFD and BIFD are equivalent. Both IFD and BIFD can be located anywhere in the TIFF file. Every 'page' in a multi-page TIFF, either classic TIFF or BigTIFF, is represented by exactly one IFD and one BIFD respectively. 

include::../requirements/core/bifd.adoc[]

The last item in the requirement  allows a single procedure to retrieve any integer value, and makes reading more robust, and saves disk space in some situations.

A BIFD consists of an 8-byte count of the number of directory entries (i.e., the number of fields), followed by a sequence of 20-byte field
entries, followed by an 8-byte offset of the next BIFD (or 0 if no other BIFD is required).

Every _Big Directory Entry_ takes up exactly 20 bytes in BigTIFF, and the complete BIFD looks like this:

[#bigtiff-ifd-structure,reftext='{table-caption} {counter:table-num}']
.BigTIFF Image File Directory (BIFD)
[width = "100%",options="header",cols="20h,~,~"]
|===
| Offset {set:cellbgcolor:#EEEEEE} | Datatype | Value
| 0 {set:cellbgcolor:#FFFFFF} | uint64 | Number of big directory entries in BIFD (B)
| 8+0*20 | Big directory entry structure (see <<bigtiff-de-structure>>) | First tag data in a TIFF field
| 8+1*20 | Big directory entry structure (see <<bigtiff-de-structure>>) | Second tag data in a TIFF field
3+| ...
| 8+(B-1)*20 | Big directory entry structure (see <<bigtiff-de-structure>>) | Last tag data in a TIFF field
| 8+B*20 | uint64 | Offset to next BIFD, if there is a next BIFD or 0 otherwise
|===

A _TIFF field_ is a logical entity consisting of TIFF tag and its value. This logical concept is implemented as a _Directory Entry_ in the TIFF version 6 and it is implemented in here as a _Big Directory Entry_, plus the actual value if it does not fit into the value/offset part, the last 8 bytes of the BIFD Entry.

[#bigtiff-de-structure,reftext='{table-caption} {counter:table-num}']
.BigTIFF Tag structure
[width = "100%",options="header",cols="10h,~,~""]
|===
| Offset {set:cellbgcolor:#EEEEEE} | Datatype | Value
| 0 {set:cellbgcolor:#FFFFFF} | uint16 | Tag identifying code ^1^
| 2 | uint16 | Datatype of tag data. See <<datatype-values>>
| 4 | uint64 | Number of values (n) (it is not the total number of bytes but the number of values)
| 12 | n * Tag data or uint64 offset | Tag data (if the size of n * Tag data is lower or equal to 64 bits) or offset to tag data (otherwise)
3+|^1^ See a list of codes in the TIFF version 6 specification. The GeoTIFF standard adds some extra TIFF tag identifiers.
|===

Each _TIFF field_ has an associated _Number of values_ (n). This means that all fields are actually one-dimensional arrays, even though most fields contain only a single value. 

The same rule for value 'inlining' the tag data applies to both classic TIFF and BigTIFF, only the threshold size differs. Above the threshold values are pointed by an offset and written elsewhere.


Some good practices inherited from TIFF but not specified in <<AdobeTIFF6>> are:

* _Number of values_ (n) cannot be zero.
* Offset to tag data in multiple tags cannot be shared (e.g. Tag A and Tag B that not point to the same offset).
* Offset to tag data cannot point to the same fragment of the file (e.g. Tag A points to an area of m bytes, Tag B cannot point to part of the same area).

The following table contains the _Tag_ datatypes that are defined in BigTIFF, in addition to the ones defined in the <<AdobeTIFF6>>  (see the last part of <<datatype-values>>)

[#datatype-values,reftext='{table-caption} {counter:table-num}']
.BigTIFF Datatype Tag values
[width = "100%",options="header", cols="10,15,~,~"]
|===
| Value {set:cellbgcolor:#EEEEEE} | Name | Description | Source
| 16 | LONG8 (uint64) | 64-bit (8-byte) unsigned integer | BigTIFF
| 17 | SLONG8 (int64) | 64-bit (8-byte) signed integer | BigTIFF
| 18 | IFD8 | A uint64 IFD offset | BigTIFF
|===

include::../recommendations/core/PER_long8.adoc[]

NOTE: For future versions it would be useful to add a new datatype "UTF8". This will allow for better metadata handling and internationalization.
